
package Formularios;

import Classes.Dados;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class frmLogin extends javax.swing.JFrame {
private Dados clsdados;

public void setDados(Dados clsdados){
    this.clsdados = clsdados;
}
    
    public frmLogin() {
        initComponents();
        txtSenha.setBackground(new java.awt.Color(0,0,0,1));
        txtUsuario.setBackground(new java.awt.Color(0,0,0,1));
        txtViewSenha.setBackground(new java.awt.Color(0,0,0,1));
        txtViewSenha.setVisible(false);
        erroSenha.setVisible(false);
    }
 
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        cmdLogin = new javax.swing.JButton();
        cmdSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtViewSenha = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        CheckBox = new javax.swing.JCheckBox();
        erroSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lgin");
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(51, 61, 71));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 176));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(32, 34, 37));
        jPanel4.setLayout(null);

        label1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Usuario:");
        jPanel4.add(label1);
        label1.setBounds(10, 40, 50, 19);

        label2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Senha:");
        jPanel4.add(label2);
        label2.setBounds(10, 70, 43, 19);

        cmdLogin.setBackground(new java.awt.Color(51, 61, 71));
        cmdLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdLogin.setForeground(new java.awt.Color(255, 255, 255));
        cmdLogin.setText("Login");
        cmdLogin.setBorder(null);
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLogin);
        cmdLogin.setBounds(150, 110, 88, 30);

        cmdSair.setBackground(new java.awt.Color(51, 61, 71));
        cmdSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdSair.setForeground(new java.awt.Color(255, 255, 255));
        cmdSair.setText("Sair");
        cmdSair.setBorder(null);
        cmdSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSairActionPerformed(evt);
            }
        });
        jPanel4.add(cmdSair);
        cmdSair.setBounds(60, 110, 84, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 0, 250, 30);

        jPanel1.setBackground(new java.awt.Color(51, 61, 71));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        txtUsuario.setBackground(new java.awt.Color(51, 61, 71));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(10, 0, 300, 30);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(60, 40, 320, 30);

        jPanel2.setBackground(new java.awt.Color(51, 61, 71));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        txtViewSenha.setBackground(new java.awt.Color(51, 61, 71));
        txtViewSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtViewSenha.setBorder(null);
        txtViewSenha.setOpaque(false);
        txtViewSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(txtViewSenha);
        txtViewSenha.setBounds(10, 0, 300, 30);

        txtSenha.setBackground(new java.awt.Color(51, 61, 71));
        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setBorder(null);
        txtSenha.setOpaque(false);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(txtSenha);
        txtSenha.setBounds(10, 0, 300, 30);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(60, 70, 320, 30);

        CheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox.setText("ver senha");
        CheckBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CheckBox.setOpaque(false);
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });
        jPanel4.add(CheckBox);
        CheckBox.setBounds(240, 110, 90, 23);

        erroSenha.setForeground(new java.awt.Color(153, 0, 0));
        erroSenha.setText("*senha ou/e usuario incorretos");
        jPanel4.add(erroSenha);
        erroSenha.setBounds(60, 100, 280, 10);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(10, 10, 400, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Login");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void cmdSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSairActionPerformed
        //Botão para saida do Login
        this.dispose();
    }//GEN-LAST:event_cmdSairActionPerformed

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
       // Botão login
       
       if (clsdados.validarUsuarios(txtUsuario.getText(),new String(txtSenha.getPassword()))){
           erroSenha.setVisible(true);
           txtUsuario.setText("");
           txtSenha.setText("");
           txtUsuario.requestFocusInWindow();
           return;
       }
       
       frmMenu frmmenu = new frmMenu();
       this.setVisible(false);
       frmmenu.setDados(clsdados);
       frmmenu.setExtendedState(JFrame.MAXIMIZED_BOTH);
       frmmenu.setVisible(true);
    }//GEN-LAST:event_cmdLoginActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxActionPerformed
if(CheckBox.isSelected()){
    txtViewSenha.setText(txtSenha.getText());    
    txtViewSenha.setVisible(true);txtSenha.setVisible(false);
    }else{
    txtSenha.setText(txtViewSenha.getText());
    txtViewSenha.setVisible(false);txtSenha.setVisible(true);
/*
      if(CheckBox.isSelected()){
    PasswordViewField.setText(PasswordField.getText());    
    PasswordViewField.setVisible(true);PasswordField.setVisible(false);
    }else{
    PasswordField.setText(PasswordViewField.getText());
    PasswordViewField.setVisible(false);PasswordField.setVisible(true);
    }
        
    */    
}        
    }//GEN-LAST:event_CheckBoxActionPerformed

    private void txtViewSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JButton cmdLogin;
    private javax.swing.JButton cmdSair;
    private javax.swing.JLabel erroSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtViewSenha;
    // End of variables declaration//GEN-END:variables
}
